repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.7
  hooks:
  - id: ruff
    exclude: ^(examples/)

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.5.2
  hooks:
  - id: add-license-headers
    args:
    - --start_year=2023
